#!/usr/bin/env tsx
// Fetches the community-curated index at claudemarketplaces.com/sitemap.xml
// and generates src/generated/marketplace-tokens.ts. The output is the union
// of `<owner>`, `<repo>`, and `<skillName>` strings parsed out of every
// individual skill page URL — those tokens drive the scanner's "is this
// skill name from a public marketplace?" check.
//
// We pull from sitemap.xml (~1200 individual skill pages) rather than
// llms.txt (~38 top-N entries) for full coverage.
//
// Run before each release: `pnpm sync-marketplace`. The generated file is
// committed so the CLI ships with a baked-in snapshot — no runtime network
// call, no audit complication.

import { mkdir, writeFile } from "node:fs/promises";

const SITEMAP_URL = "https://claudemarketplaces.com/sitemap.xml";
const OUTPUT_PATH = "src/generated/marketplace-tokens.ts";

// `https://claudemarketplaces.com/skills/<owner>/<repo>/<name>`. We skip
// `/skills/category/<slug>` (those are category indexes, not skill pages).
const SKILL_URL_RE =
  /<loc>https:\/\/claudemarketplaces\.com\/skills\/([\w.-]+)\/([\w.-]+)\/([\w.-]+)<\/loc>/g;

async function main(): Promise<void> {
  const res = await fetch(SITEMAP_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${SITEMAP_URL}`);
  const text = await res.text();

  const tokens = new Set<string>();
  let urlCount = 0;
  for (const match of text.matchAll(SKILL_URL_RE)) {
    const owner = match[1]!;
    const repo = match[2]!;
    const name = match[3]!;
    if (owner === "category") continue; // /skills/category/<slug>
    tokens.add(owner);
    tokens.add(repo);
    tokens.add(name);
    urlCount += 1;
  }

  const sorted = Array.from(tokens).sort();
  const generated = `// AUTO-GENERATED by scripts/sync-marketplace.ts. Do not edit by hand.
// Source: ${SITEMAP_URL}
// Last synced: ${new Date().toISOString()}
// Source URL count: ${urlCount}
// Token count: ${sorted.length}
//
// Each entry is one of: a GitHub owner (e.g. "anthropics", "vercel-labs"),
// a plugin repo (e.g. "superpowers", "azure-skills"), or a skill name
// (e.g. "db-query", "frontend-design"). A skill invocation like
// "superpowers:brainstorming" is treated as public-marketplace if the
// segment before the colon is in this set; an invocation like "db-query"
// matches if the whole string is in this set. See \`isShippableSkillName\`
// in src/redaction.ts.

export const KNOWN_MARKETPLACE_TOKENS: readonly string[] = ${JSON.stringify(
    sorted,
    null,
    2
  )};
`;

  await mkdir("src/generated", { recursive: true });
  await writeFile(OUTPUT_PATH, generated);
  process.stdout.write(
    `wrote ${sorted.length} tokens from ${urlCount} skill URLs to ${OUTPUT_PATH}\n`
  );
}

main().catch((err) => {
  process.stderr.write(`sync-marketplace failed: ${String(err)}\n`);
  process.exit(1);
});
