#!/usr/bin/env tsx
// Fetches the community-curated index at claudemarketplaces.com/sitemap.xml
// and generates src/generated/marketplace-tokens.ts. The output is the union
// of FULL invocation names parsed from every `/skills/<owner>/<repo>/<name>`
// URL in the sitemap:
//
//   `<repo>:<name>` (namespaced form, e.g. `superpowers:brainstorming`)
//   `<name>`        (bare form, e.g. `db-query`)
//
// We DO NOT emit just `<owner>` or `<repo>` — that would enable namespace-
// prefix matching, which lets short tokens like `ai`, `cli`, `pdf` collide
// with user-private invocations (e.g. `ai:omni-internal` would falsely
// classify as public). The trust gate must match invocation strings
// EXACTLY; the recheck:deep CRITICAL finding that this fix addresses
// explains the namespace-squatting attack in detail.
//
// Run before each release: `pnpm sync-marketplace`. The generated file is
// committed so the CLI ships with a baked-in snapshot — no runtime network
// call, no audit complication.

import { mkdir, writeFile } from "node:fs/promises";

const SITEMAP_URL = "https://claudemarketplaces.com/sitemap.xml";
const OUTPUT_PATH = "src/generated/marketplace-tokens.ts";

// `https://claudemarketplaces.com/skills/<owner>/<repo>/<name>`. We skip
// `/skills/category/<slug>` (those are category indexes, not skill pages).
const SKILL_URL_RE =
  /<loc>https:\/\/claudemarketplaces\.com\/skills\/([\w.-]+)\/([\w.-]+)\/([\w.-]+)<\/loc>/g;

// Minimum URL count we expect in the sitemap. If we see fewer than this,
// the site likely changed its URL scheme and we'd be writing a degraded
// (empty-ish) snapshot. Fail loud rather than silently ship under-
// classification.
const MIN_URL_COUNT = 500;

async function main(): Promise<void> {
  const res = await fetch(SITEMAP_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${SITEMAP_URL}`);
  const text = await res.text();

  const invocations = new Set<string>();
  let urlCount = 0;
  for (const match of text.matchAll(SKILL_URL_RE)) {
    const owner = match[1]!;
    const repo = match[2]!;
    const name = match[3]!;
    if (owner === "category") continue; // /skills/category/<slug>
    urlCount += 1;
    // Three invocation forms per URL — all exact-match-shippable, no
    // prefix expansion. The plugin's actual namespace in its
    // marketplace.json doesn't always match the GitHub repo name; some
    // plugins surface skills as `<skillName>:<skillName>` (e.g.
    // `frontend-design:frontend-design`). Emitting all three covers the
    // patterns observed in real session JSONLs.
    invocations.add(`${repo}:${name}`); // namespaced via repo
    invocations.add(`${name}:${name}`); // namespaced via skill name
    invocations.add(name); // single-skill / bare invocation
  }

  if (urlCount < MIN_URL_COUNT) {
    throw new Error(
      `sitemap returned only ${urlCount} skill URLs; expected >= ${MIN_URL_COUNT}. The sitemap URL scheme may have changed — refusing to ship a degraded token list. Investigate ${SITEMAP_URL} before retrying.`
    );
  }

  const sorted = Array.from(invocations).sort();
  const generated = `// AUTO-GENERATED by scripts/sync-marketplace.ts. Do not edit by hand.
// Source: ${SITEMAP_URL}
// Source URL count: ${urlCount}
// Invocation count: ${sorted.length}
//
// Each entry is a FULL skill invocation name — either a namespaced form
// like "superpowers:brainstorming" or a bare form like "db-query". The
// scanner and schema both check user-emitted skill names against this
// set via exact match (no prefix expansion). See \`isShippableSkillName\`
// in src/redaction.ts for the predicate.

export const KNOWN_MARKETPLACE_INVOCATIONS: readonly string[] = ${JSON.stringify(
    sorted,
    null,
    2
  )};
`;

  await mkdir("src/generated", { recursive: true });
  await writeFile(OUTPUT_PATH, generated);
  process.stdout.write(
    `wrote ${sorted.length} invocations from ${urlCount} skill URLs to ${OUTPUT_PATH}\n`
  );
}

main().catch((err) => {
  process.stderr.write(`sync-marketplace failed: ${String(err)}\n`);
  process.exit(1);
});
